export * from './home';
export * from './cart';
export * from './Menu';
export * from './register';
export * from './Login';
export * from './admin/editarProdutos';
export * from './admin/newProducts';
export * from './admin/orders';
export * from './admin/products';
